<?xml version="1.0" encoding="UTF-8" ?>

<testsuite failures="0" time="0.04" errors="1" skipped="0" tests="0" name="models.UserYabeTest">
  <testcase classname="models.UserYabeTest" name="first" time="0.04">
                        <error type="" message="A java.lang.RuntimeException has been caught, Cannot load fixture data.yml: Cannot load fixture data.yml, duplicate id &amp;apos;bob&amp;apos; for type models.user.UserYabe">
        <![CDATA[
          In /test/models/UserYabeTest.java, line 14
          
                  Fixtures.loadModels(&quot;data.yml&quot;); :
          
        ]]>
        </error>
                  <system-err>
            java.lang.RuntimeException: Cannot load fixture data.yml: Cannot load fixture data.yml, duplicate id &apos;bob&apos; for type models.user.UserYabe
	at play.test.Fixtures.loadModels(Fixtures.java:274)
	at play.test.Fixtures.loadModels(Fixtures.java:174)
	at models.UserYabeTest.first(UserYabeTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at play.test.PlayJUnitRunner$StartPlay$2$1.evaluate(PlayJUnitRunner.java:123)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at play.test.PlayJUnitRunner.run(PlayJUnitRunner.java:67)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
	at play.test.TestEngine.run(TestEngine.java:187)
	at controllers.TestRunner$1.doJobWithResult(TestRunner.java:79)
	at controllers.TestRunner$1.doJobWithResult(TestRunner.java:1)
	at play.jobs.Job$2.apply(Job.java:196)
	at play.db.jpa.JPA.withTransaction(JPA.java:262)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:261)
	at play.jobs.Job.withinFilter(Job.java:175)
	at play.jobs.Job.call(Job.java:194)
	at play.jobs.Job$1.call(Job.java:117)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Cannot load fixture data.yml, duplicate id &apos;bob&apos; for type models.user.UserYabe
	at play.test.Fixtures.loadModels(Fixtures.java:225)
	... 48 more

          </system-err>  
        }
            </testcase>
</testsuite>